package cn.epalmpay.analoy.entity.base;

import java.util.Date;

public class EquipMent {
	/**
	 * 未激活
	 */
	public static final Integer ACTIVATE_STATUS_NO_ACTIVED = 1;
	/**
	 * 激活未注册
	 */
	public static final Integer ACTIVATE_STATUS_NO_REGISTED = 2;
	/**
	 * 激活已注册
	 */
	public static final Integer ACTIVATE_STATUS_REGISTED = 3;

	/**
	 * 钱袋宝
	 */
	public static final Integer EQTYPE_QIANDAIBAO = 1;
	/**
	 * 中汇
	 */
	public static final Integer EQTYPE_ZHONGHUI = 2;
	/**
	 * 韩鑫
	 */
	public static final Integer EQTYPE_HANXIN = 3;

	/**
	 * 已开通
	 */
	public static final Integer OPEN_STATUS = 1;
	/**
	 * 未开通
	 */
	public static final Integer NOT_OPEN_STATUS = 1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.eqno
	 *
	 * @mbggenerated
	 */
	private String eqno;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.agentno
	 *
	 * @mbggenerated
	 */
	private String agentno;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.agentname
	 *
	 * @mbggenerated
	 */
	private String agentname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.eqtype
	 *
	 * @mbggenerated
	 */
	private Integer eqtype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.status
	 *
	 * @mbggenerated
	 */
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.loginName
	 *
	 * @mbggenerated
	 */
	private String loginname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.password
	 *
	 * @mbggenerated
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.position
	 *
	 * @mbggenerated
	 */
	private String position;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.appVersion
	 *
	 * @mbggenerated
	 */
	private String appversion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.product
	 *
	 * @mbggenerated
	 */
	private String product;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.username
	 *
	 * @mbggenerated
	 */
	private String username;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.receivecardno
	 *
	 * @mbggenerated
	 */
	private String receivecardno;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.activated
	 *
	 * @mbggenerated
	 */
	private Integer activated;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.createdAt
	 *
	 * @mbggenerated
	 */
	private Date createdat;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.updatedAt
	 *
	 * @mbggenerated
	 */
	private Date updatedat;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column equipment.licenseCode
	 *
	 * @mbggenerated
	 */
	private String licensecode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.id
	 *
	 * @return the value of equipment.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.id
	 *
	 * @param id
	 *            the value for equipment.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.eqno
	 *
	 * @return the value of equipment.eqno
	 *
	 * @mbggenerated
	 */
	public String getEqno() {
		return eqno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.eqno
	 *
	 * @param eqno
	 *            the value for equipment.eqno
	 *
	 * @mbggenerated
	 */
	public void setEqno(String eqno) {
		this.eqno = eqno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.agentno
	 *
	 * @return the value of equipment.agentno
	 *
	 * @mbggenerated
	 */
	public String getAgentno() {
		return agentno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.agentno
	 *
	 * @param agentno
	 *            the value for equipment.agentno
	 *
	 * @mbggenerated
	 */
	public void setAgentno(String agentno) {
		this.agentno = agentno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.agentname
	 *
	 * @return the value of equipment.agentname
	 *
	 * @mbggenerated
	 */
	public String getAgentname() {
		return agentname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.agentname
	 *
	 * @param agentname
	 *            the value for equipment.agentname
	 *
	 * @mbggenerated
	 */
	public void setAgentname(String agentname) {
		this.agentname = agentname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.eqtype
	 *
	 * @return the value of equipment.eqtype
	 *
	 * @mbggenerated
	 */
	public Integer getEqtype() {
		return eqtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.eqtype
	 *
	 * @param eqtype
	 *            the value for equipment.eqtype
	 *
	 * @mbggenerated
	 */
	public void setEqtype(Integer eqtype) {
		this.eqtype = eqtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.status
	 *
	 * @return the value of equipment.status
	 *
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.status
	 *
	 * @param status
	 *            the value for equipment.status
	 *
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.loginName
	 *
	 * @return the value of equipment.loginName
	 *
	 * @mbggenerated
	 */
	public String getLoginname() {
		return loginname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.loginName
	 *
	 * @param loginname
	 *            the value for equipment.loginName
	 *
	 * @mbggenerated
	 */
	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.password
	 *
	 * @return the value of equipment.password
	 *
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.password
	 *
	 * @param password
	 *            the value for equipment.password
	 *
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.position
	 *
	 * @return the value of equipment.position
	 *
	 * @mbggenerated
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.position
	 *
	 * @param position
	 *            the value for equipment.position
	 *
	 * @mbggenerated
	 */
	public void setPosition(String position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.appVersion
	 *
	 * @return the value of equipment.appVersion
	 *
	 * @mbggenerated
	 */
	public String getAppversion() {
		return appversion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.appVersion
	 *
	 * @param appversion
	 *            the value for equipment.appVersion
	 *
	 * @mbggenerated
	 */
	public void setAppversion(String appversion) {
		this.appversion = appversion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.product
	 *
	 * @return the value of equipment.product
	 *
	 * @mbggenerated
	 */
	public String getProduct() {
		return product;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.product
	 *
	 * @param product
	 *            the value for equipment.product
	 *
	 * @mbggenerated
	 */
	public void setProduct(String product) {
		this.product = product;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.username
	 *
	 * @return the value of equipment.username
	 *
	 * @mbggenerated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.username
	 *
	 * @param username
	 *            the value for equipment.username
	 *
	 * @mbggenerated
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.receivecardno
	 *
	 * @return the value of equipment.receivecardno
	 *
	 * @mbggenerated
	 */
	public String getReceivecardno() {
		return receivecardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.receivecardno
	 *
	 * @param receivecardno
	 *            the value for equipment.receivecardno
	 *
	 * @mbggenerated
	 */
	public void setReceivecardno(String receivecardno) {
		this.receivecardno = receivecardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.activated
	 *
	 * @return the value of equipment.activated
	 *
	 * @mbggenerated
	 */
	public Integer getActivated() {
		return activated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.activated
	 *
	 * @param activated
	 *            the value for equipment.activated
	 *
	 * @mbggenerated
	 */
	public void setActivated(Integer activated) {
		this.activated = activated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.createdAt
	 *
	 * @return the value of equipment.createdAt
	 *
	 * @mbggenerated
	 */
	public Date getCreatedat() {
		return createdat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.createdAt
	 *
	 * @param createdat
	 *            the value for equipment.createdAt
	 *
	 * @mbggenerated
	 */
	public void setCreatedat(Date createdat) {
		this.createdat = createdat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.updatedAt
	 *
	 * @return the value of equipment.updatedAt
	 *
	 * @mbggenerated
	 */
	public Date getUpdatedat() {
		return updatedat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.updatedAt
	 *
	 * @param updatedat
	 *            the value for equipment.updatedAt
	 *
	 * @mbggenerated
	 */
	public void setUpdatedat(Date updatedat) {
		this.updatedat = updatedat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column equipment.licenseCode
	 *
	 * @return the value of equipment.licenseCode
	 *
	 * @mbggenerated
	 */
	public String getLicensecode() {
		return licensecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column equipment.licenseCode
	 *
	 * @param licensecode
	 *            the value for equipment.licenseCode
	 *
	 * @mbggenerated
	 */
	public void setLicensecode(String licensecode) {
		this.licensecode = licensecode;
	}
}