package cn.epalmpay.analoy.entity;

import java.util.Date;

public class EquipMent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.eqno
     *
     * @mbggenerated
     */
    private String eqno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.agentno
     *
     * @mbggenerated
     */
    private String agentno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.agentname
     *
     * @mbggenerated
     */
    private String agentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.eqtype
     *
     * @mbggenerated
     */
    private Integer eqtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.createdAt
     *
     * @mbggenerated
     */
    private Date createdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.updateAt
     *
     * @mbggenerated
     */
    private Date updateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.id
     *
     * @return the value of equipment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.id
     *
     * @param id the value for equipment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.eqno
     *
     * @return the value of equipment.eqno
     *
     * @mbggenerated
     */
    public String getEqno() {
        return eqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.eqno
     *
     * @param eqno the value for equipment.eqno
     *
     * @mbggenerated
     */
    public void setEqno(String eqno) {
        this.eqno = eqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.agentno
     *
     * @return the value of equipment.agentno
     *
     * @mbggenerated
     */
    public String getAgentno() {
        return agentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.agentno
     *
     * @param agentno the value for equipment.agentno
     *
     * @mbggenerated
     */
    public void setAgentno(String agentno) {
        this.agentno = agentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.agentname
     *
     * @return the value of equipment.agentname
     *
     * @mbggenerated
     */
    public String getAgentname() {
        return agentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.agentname
     *
     * @param agentname the value for equipment.agentname
     *
     * @mbggenerated
     */
    public void setAgentname(String agentname) {
        this.agentname = agentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.eqtype
     *
     * @return the value of equipment.eqtype
     *
     * @mbggenerated
     */
    public Integer getEqtype() {
        return eqtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.eqtype
     *
     * @param eqtype the value for equipment.eqtype
     *
     * @mbggenerated
     */
    public void setEqtype(Integer eqtype) {
        this.eqtype = eqtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.status
     *
     * @return the value of equipment.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.status
     *
     * @param status the value for equipment.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.createdAt
     *
     * @return the value of equipment.createdAt
     *
     * @mbggenerated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.createdAt
     *
     * @param createdat the value for equipment.createdAt
     *
     * @mbggenerated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.updateAt
     *
     * @return the value of equipment.updateAt
     *
     * @mbggenerated
     */
    public Date getUpdateat() {
        return updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.updateAt
     *
     * @param updateat the value for equipment.updateAt
     *
     * @mbggenerated
     */
    public void setUpdateat(Date updateat) {
        this.updateat = updateat;
    }
}