package cn.epalmpay.analoy.entity;

import java.util.Date;

public class Tbank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbank.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbank.bankDeposit
     *
     * @mbggenerated
     */
    private String bankdeposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbank.unionBankNo
     *
     * @mbggenerated
     */
    private String unionbankno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbank.createdAt
     *
     * @mbggenerated
     */
    private Date createdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbank.updateAt
     *
     * @mbggenerated
     */
    private Date updateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbank.id
     *
     * @return the value of tbank.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbank.id
     *
     * @param id the value for tbank.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbank.bankDeposit
     *
     * @return the value of tbank.bankDeposit
     *
     * @mbggenerated
     */
    public String getBankdeposit() {
        return bankdeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbank.bankDeposit
     *
     * @param bankdeposit the value for tbank.bankDeposit
     *
     * @mbggenerated
     */
    public void setBankdeposit(String bankdeposit) {
        this.bankdeposit = bankdeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbank.unionBankNo
     *
     * @return the value of tbank.unionBankNo
     *
     * @mbggenerated
     */
    public String getUnionbankno() {
        return unionbankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbank.unionBankNo
     *
     * @param unionbankno the value for tbank.unionBankNo
     *
     * @mbggenerated
     */
    public void setUnionbankno(String unionbankno) {
        this.unionbankno = unionbankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbank.createdAt
     *
     * @return the value of tbank.createdAt
     *
     * @mbggenerated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbank.createdAt
     *
     * @param createdat the value for tbank.createdAt
     *
     * @mbggenerated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbank.updateAt
     *
     * @return the value of tbank.updateAt
     *
     * @mbggenerated
     */
    public Date getUpdateat() {
        return updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbank.updateAt
     *
     * @param updateat the value for tbank.updateAt
     *
     * @mbggenerated
     */
    public void setUpdateat(Date updateat) {
        this.updateat = updateat;
    }
}