package cn.epalmpay.analoy.entity;

import java.util.Date;

public class Tbank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbank.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbank.bankName
     *
     * @mbggenerated
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbank.createdAt
     *
     * @mbggenerated
     */
    private Date createdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbank.updateAt
     *
     * @mbggenerated
     */
    private Date updateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbank.id
     *
     * @return the value of tbank.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbank.id
     *
     * @param id the value for tbank.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbank.bankName
     *
     * @return the value of tbank.bankName
     *
     * @mbggenerated
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbank.bankName
     *
     * @param bankname the value for tbank.bankName
     *
     * @mbggenerated
     */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbank.createdAt
     *
     * @return the value of tbank.createdAt
     *
     * @mbggenerated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbank.createdAt
     *
     * @param createdat the value for tbank.createdAt
     *
     * @mbggenerated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbank.updateAt
     *
     * @return the value of tbank.updateAt
     *
     * @mbggenerated
     */
    public Date getUpdateat() {
        return updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbank.updateAt
     *
     * @param updateat the value for tbank.updateAt
     *
     * @mbggenerated
     */
    public void setUpdateat(Date updateat) {
        this.updateat = updateat;
    }
}