package cn.epalmpay.analoy.entity;

import java.util.Date;

public class TradeOrder {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tradeorder.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tradeorder.transactional_number
	 *
	 * @mbggenerated
	 */
	private String transactionalNumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tradeorder.payType
	 *
	 * @mbggenerated
	 */
	private Integer paytype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tradeorder.settleBankName
	 *
	 * @mbggenerated
	 */
	private String settlebankname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tradeorder.cardType
	 *
	 * @mbggenerated
	 */
	private Integer cardtype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tradeorder.settleCardNo
	 *
	 * @mbggenerated
	 */
	private String settlecardno;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tradeorder.money
	 *
	 * @mbggenerated
	 */
	private Double money;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tradeorder.fee
	 *
	 * @mbggenerated
	 */
	private Double fee;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tradeorder.settleMoney
	 *
	 * @mbggenerated
	 */
	private Double settlemoney;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tradeorder.eq_id
	 *
	 * @mbggenerated
	 */
	private Integer eqId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tradeorder.createdAt
	 *
	 * @mbggenerated
	 */
	private Date createdat;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tradeorder.id
	 *
	 * @return the value of tradeorder.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tradeorder.id
	 *
	 * @param id
	 *            the value for tradeorder.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tradeorder.transactional_number
	 *
	 * @return the value of tradeorder.transactional_number
	 *
	 * @mbggenerated
	 */
	public String getTransactionalNumber() {
		return transactionalNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tradeorder.transactional_number
	 *
	 * @param transactionalNumber
	 *            the value for tradeorder.transactional_number
	 *
	 * @mbggenerated
	 */
	public void setTransactionalNumber(String transactionalNumber) {
		this.transactionalNumber = transactionalNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tradeorder.payType
	 *
	 * @return the value of tradeorder.payType
	 *
	 * @mbggenerated
	 */
	public Integer getPaytype() {
		return paytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tradeorder.payType
	 *
	 * @param paytype
	 *            the value for tradeorder.payType
	 *
	 * @mbggenerated
	 */
	public void setPaytype(Integer paytype) {
		this.paytype = paytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tradeorder.settleBankName
	 *
	 * @return the value of tradeorder.settleBankName
	 *
	 * @mbggenerated
	 */
	public String getSettlebankname() {
		return settlebankname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tradeorder.settleBankName
	 *
	 * @param settlebankname
	 *            the value for tradeorder.settleBankName
	 *
	 * @mbggenerated
	 */
	public void setSettlebankname(String settlebankname) {
		this.settlebankname = settlebankname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tradeorder.cardType
	 *
	 * @return the value of tradeorder.cardType
	 *
	 * @mbggenerated
	 */
	public Integer getCardtype() {
		return cardtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tradeorder.cardType
	 *
	 * @param cardtype
	 *            the value for tradeorder.cardType
	 *
	 * @mbggenerated
	 */
	public void setCardtype(Integer cardtype) {
		this.cardtype = cardtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tradeorder.settleCardNo
	 *
	 * @return the value of tradeorder.settleCardNo
	 *
	 * @mbggenerated
	 */
	public String getSettlecardno() {
		return settlecardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tradeorder.settleCardNo
	 *
	 * @param settlecardno
	 *            the value for tradeorder.settleCardNo
	 *
	 * @mbggenerated
	 */
	public void setSettlecardno(String settlecardno) {
		this.settlecardno = settlecardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tradeorder.money
	 *
	 * @return the value of tradeorder.money
	 *
	 * @mbggenerated
	 */
	public Double getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tradeorder.money
	 *
	 * @param money
	 *            the value for tradeorder.money
	 *
	 * @mbggenerated
	 */
	public void setMoney(Double money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tradeorder.fee
	 *
	 * @return the value of tradeorder.fee
	 *
	 * @mbggenerated
	 */
	public Double getFee() {
		return fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tradeorder.fee
	 *
	 * @param fee
	 *            the value for tradeorder.fee
	 *
	 * @mbggenerated
	 */
	public void setFee(Double fee) {
		this.fee = fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tradeorder.settleMoney
	 *
	 * @return the value of tradeorder.settleMoney
	 *
	 * @mbggenerated
	 */
	public Double getSettlemoney() {
		return settlemoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tradeorder.settleMoney
	 *
	 * @param settlemoney
	 *            the value for tradeorder.settleMoney
	 *
	 * @mbggenerated
	 */
	public void setSettlemoney(Double settlemoney) {
		this.settlemoney = settlemoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tradeorder.eq_id
	 *
	 * @return the value of tradeorder.eq_id
	 *
	 * @mbggenerated
	 */
	public Integer getEqId() {
		return eqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tradeorder.eq_id
	 *
	 * @param eqId
	 *            the value for tradeorder.eq_id
	 *
	 * @mbggenerated
	 */
	public void setEqId(Integer eqId) {
		this.eqId = eqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tradeorder.createdAt
	 *
	 * @return the value of tradeorder.createdAt
	 *
	 * @mbggenerated
	 */
	public Date getCreatedat() {
		return createdat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tradeorder.createdAt
	 *
	 * @param createdat
	 *            the value for tradeorder.createdAt
	 *
	 * @mbggenerated
	 */
	public void setCreatedat(Date createdat) {
		this.createdat = createdat;
	}

	private String eqno;

	public String getEqno() {
		return eqno;
	}

	public void setEqno(String eqno) {
		this.eqno = eqno;
	}

}