package cn.epalmpay.analoy.entity;

public class TradeOrderFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeorderfile.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeorderfile.filepath
     *
     * @mbggenerated
     */
    private String filepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tradeorderfile.ispushed
     *
     * @mbggenerated
     */
    private Byte ispushed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeorderfile.id
     *
     * @return the value of tradeorderfile.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeorderfile.id
     *
     * @param id the value for tradeorderfile.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeorderfile.filepath
     *
     * @return the value of tradeorderfile.filepath
     *
     * @mbggenerated
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeorderfile.filepath
     *
     * @param filepath the value for tradeorderfile.filepath
     *
     * @mbggenerated
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tradeorderfile.ispushed
     *
     * @return the value of tradeorderfile.ispushed
     *
     * @mbggenerated
     */
    public Byte getIspushed() {
        return ispushed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tradeorderfile.ispushed
     *
     * @param ispushed the value for tradeorderfile.ispushed
     *
     * @mbggenerated
     */
    public void setIspushed(Byte ispushed) {
        this.ispushed = ispushed;
    }
}