package cn.epalmpay.analoy.mapper;

import java.util.List;
import java.util.Map;

import cn.epalmpay.analoy.entity.EquipMent;

public interface EquipMentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated
     */
    int insert(EquipMent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated
     */
    EquipMent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated
     */
    List<EquipMent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EquipMent record);

	List<Map<String, Object>> getEqnoByStatus();

	int updateStatus(String[] ids);

	EquipMent getEuipMent(int parseInt, String eqno);
}