package cn.epalmpay.analoy.mapper;

import java.util.List;
import java.util.Map;

import cn.epalmpay.analoy.entity.base.EquipMent;

public interface EquipMentMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table equipment
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table equipment
	 *
	 * @mbggenerated
	 */
	int insert(EquipMent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table equipment
	 *
	 * @mbggenerated
	 */
	EquipMent selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table equipment
	 *
	 * @mbggenerated
	 */
	List<EquipMent> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table equipment
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(EquipMent record);

	/**
	 * 查询设备信息为未开通状态的所有设备
	 * @param status TODO
	 * 
	 * @return
	 */
	List<Map<String, Object>> getEqnoByStatus(int status);

	int updateStatus(String[] ids);

	/**
	 * 根据设备编号设备类型查询设备为开通状态的设备信息
	 * 
	 * @param status
	 * @param eqno
	 * @return
	 */
	EquipMent getEuipMent(int status, String eqno);

	/**
	 * 根据设备绑定手机号以及密码查询设备信息
	 * 
	 * @param loginName
	 * @param password
	 * @return
	 */
	Map<String, Object> login(String loginName, String password);

	/**
	 * 根据终端号以及支付通道查询终端信息
	 * 
	 * @param eqno
	 * @param eqtype
	 * @return
	 */
	EquipMent getEquipmentByEqnoAndType(String eqno, int eqtype);

	/**
	 * 根据设备编号以及激活码查询设备信息
	 * 
	 * @param ksnNo
	 * @param licenseCode
	 * @return
	 */
	EquipMent getEquipmentByEqnoAndCode(String ksnNo, String licenseCode);

	/**
	 * 根据设备编号、设备类型更改设备激活状态
	 * 
	 * @param ksnNo
	 * @param eqtypeZhonghui
	 * @param activatedCode
	 * @return
	 */
	int activatedByKsnNo(String ksnNo, int eqtypeZhonghui, int activatedCode);

	int updateEquipment(Map<String, Object> params);

	/**
	 * 查询总的终端数
	 * 
	 * @return
	 */
	int count();

	/**
	 * 查询终端记录
	 * 
	 * @return
	 */
	List<Map<String, Object>> getList();

	/**
	 * 根据手机号查找设备号
	 * 
	 * @param mobile
	 * @param eqtypeZhonghui
	 * @return
	 */
	EquipMent getEqByMobileAndEqtype(String mobile, Integer eqtypeZhonghui);
}