package cn.epalmpay.analoy.mapper;

import java.util.List;
import java.util.Map;

import cn.epalmpay.analoy.entity.base.EquipMent;

public interface EquipMentMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table equipment
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table equipment
	 *
	 * @mbggenerated
	 */
	int insert(EquipMent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table equipment
	 *
	 * @mbggenerated
	 */
	EquipMent selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table equipment
	 *
	 * @mbggenerated
	 */
	List<EquipMent> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table equipment
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(EquipMent record);

	List<Map<String, Object>> getEqnoByStatus();

	int updateStatus(String[] ids);

	EquipMent getEuipMent(int status, String eqno);

	Map<String, Object> getEqByEqno(String eqno);

	Map<String, Object> login(String loginName, String password);

	List<Map<String, Object>> getEquipmentByEqnoAndType(String eqno, int eqtype);

	EquipMent getEquipmentByEqnoAndCode(String ksnNo, String licenseCode);

	int activatedByKsnNo(String ksnNo, int eqtypeZhonghui, int activatedCode);

	int updateEquipment(Map<String, Object> params);

	/**
	 * 查询总的终端数
	 * 
	 * @return
	 */
	int count();

	/**
	 * 查询终端记录
	 * 
	 * @return
	 */
	List<Map<String, Object>> getList();

	/**
	 * 根据手机号查找设备号
	 * 
	 * @param mobile
	 * @param eqtypeZhonghui
	 * @return
	 */
	EquipMent getEqByMobileAndEqtype(String mobile, Integer eqtypeZhonghui);
}