package cn.epalmpay.analoy.mapper;

import java.util.List;
import java.util.Map;

import cn.epalmpay.analoy.entity.base.TradeOrderFile;

public interface TradeOrderFileMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tradeorderfile
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tradeorderfile
	 *
	 * @mbggenerated
	 */
	int insert(TradeOrderFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tradeorderfile
	 *
	 * @mbggenerated
	 */
	TradeOrderFile selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tradeorderfile
	 *
	 * @mbggenerated
	 */
	List<TradeOrderFile> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tradeorderfile
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TradeOrderFile record);

	void savepath(String saveFilePath);

	List<Map<String, Object>> findFileUrlByIsPushed(int ispushed);

	int updateRecordFile(String[] ids);

	/**
	 * 根据文件名查找未推送的文件
	 * 
	 * @param saveFilePath
	 * @param pushed TODO
	 * @return
	 */
	List<Map<String, Object>> getFiles(String saveFilePath, int pushed);
}