package cn.epalmpay.analoy.mapper;

import java.util.List;
import cn.epalmpay.analoy.entity.TradeOrder;

public interface TradeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tradeorder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tradeorder
     *
     * @mbggenerated
     */
    int insert(TradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tradeorder
     *
     * @mbggenerated
     */
    TradeOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tradeorder
     *
     * @mbggenerated
     */
    List<TradeOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tradeorder
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradeOrder record);
}